name = "ResNet"
uuid = "58a9d5b1-5aa3-499c-8f61-cc8cc0c973ca"
authors = ["Anton Smirnov"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.4"
